### ISSUE TITLE
Syntax error with api key 

### ISSUE THREAD

**Issue by Camiann** [BCDigSchol/rgov-data-mining#1]
Greetings,

I have a question regarding line 19 of scrape.py. I keep receiving an invalid syntax error when I enter my API Key in the header line. I wasn't sure what that part of the line function was doing. Does your API key still work in the header? I know regulations.gov has made a lot of changes to accessibility in the last few months. 

Thanks for making your code publically available.

**Comment by annakijas1** [comment]
Hi @Camiann - I just checked the python script and was able to successfully run it, both when it is included in the header (line 19) as well as when it is NOT in the header, but only in api key line 20.

**Comment by Camiann** [comment]
@annakijas1 I got it. Thanks for the quick response.
